// Copyright 2026 The Project Contributors
// SPDX-License-Identifier: MIT

package dev.groknull.bpmner.tools.pklenumgen

import java.nio.file.Files
import java.nio.file.Path

data class GeneratedPklEnums(
    val nodeTypeNames: List<String>,
    val nodeProperties: List<String>,
)

object PklEnumGenerator {
    private val nodeClassPattern = Regex("""(?m)^\s*data\s+class\s+(Bpmn[A-Za-z0-9_]+)\s*\(""")
    private val pklPropertyPattern = Regex("""@(?:get:|field:)?PklProperty(?:\(([^)]*)\))?""")
    private val quotedStringPattern = Regex(""""((?:\\.|[^"\\])*)"""")
    private val valPattern = Regex("""\b(?:override\s+)?val\s+([A-Za-z_][A-Za-z0-9_]*)\b""")

    fun generate(
        inputFiles: List<Path>,
        outDir: Path,
    ): GeneratedPklEnums {
        require(inputFiles.isNotEmpty()) { "At least one --input file is required." }

        val sourceTexts =
            inputFiles.map { input ->
                require(Files.isRegularFile(input)) { "Input file does not exist: $input" }
                SourceText(input.toString(), Files.readString(input))
            }

        val generated =
            GeneratedPklEnums(
                nodeTypeNames = sourceTexts.flatMap { parseNodeTypeNames(it) }.distinct(),
                nodeProperties = sourceTexts.flatMap { parseNodeProperties(it) }.distinct().sorted(),
            )

        require(generated.nodeTypeNames.isNotEmpty()) {
            "No BpmnNode concrete data classes were found in ${inputFiles.joinToString()}."
        }
        require(generated.nodeProperties.isNotEmpty()) {
            "No @PklProperty annotations were found in ${inputFiles.joinToString()}."
        }

        Files.createDirectories(outDir)
        Files.writeString(outDir.resolve("NodeTypeName.pkl"), renderTypealias("NodeTypeName", generated.nodeTypeNames))
        Files.writeString(outDir.resolve("NodeProperty.pkl"), renderTypealias("NodeProperty", generated.nodeProperties))

        return generated
    }

    fun parseNodeTypeNames(source: String): List<String> = parseNodeTypeNames(SourceText("<memory>", source))

    fun parseNodeProperties(source: String): List<String> = parseNodeProperties(SourceText("<memory>", source))

    private fun parseNodeTypeNames(source: SourceText): List<String> {
        val nodeStart = source.text.indexOf("sealed interface BpmnNode")
        require(nodeStart >= 0) { "No sealed interface BpmnNode declaration found in ${source.name}." }

        val edgeStart = source.text.indexOf("data class BpmnEdge", startIndex = nodeStart)
        require(edgeStart > nodeStart) { "No data class BpmnEdge boundary found after BpmnNode in ${source.name}." }

        return nodeClassPattern
            .findAll(source.text.substring(nodeStart, edgeStart))
            .map { it.groupValues[1] }
            .map { className -> "bpmn:${className.removePrefix("Bpmn")}" }
            .toList()
    }

    private fun parseNodeProperties(source: SourceText): List<String> {
        val properties = mutableListOf<String>()
        var pendingAnnotationPath: String? = null

        source.text.lineSequence().forEachIndexed { index, line ->
            val annotation = pklPropertyPattern.find(line)
            if (annotation != null) {
                pendingAnnotationPath = parseAnnotationPath(annotation.groupValues.getOrNull(1).orEmpty())
            }

            if (pendingAnnotationPath != null) {
                val propertyName = valPattern.find(line)?.groupValues?.get(1)
                if (propertyName != null) {
                    properties.add(pendingAnnotationPath!!.ifBlank { propertyName })
                    pendingAnnotationPath = null
                } else if (startsNewDeclaration(line)) {
                    val lineNumber = index + 1
                    error("@PklProperty in ${source.name} near line $lineNumber is not followed by a val declaration.")
                }
            }
        }

        return properties
    }

    private fun parseAnnotationPath(arguments: String): String {
        if (arguments.isBlank()) {
            return ""
        }
        return quotedStringPattern
            .find(arguments)
            ?.groupValues
            ?.get(1)
            ?.replace("\\\"", "\"")
            .orEmpty()
    }

    private fun startsNewDeclaration(line: String): Boolean {
        val trimmed = line.trimStart()
        return trimmed.startsWith("data class ") ||
            trimmed.startsWith("sealed interface ") ||
            trimmed.startsWith("class ") ||
            trimmed.startsWith("object ")
    }

    private fun renderTypealias(
        name: String,
        values: List<String>,
    ): String = buildString {
        appendLine("// GENERATED by //tools/pkl-enum-gen. Do not edit.")
        appendLine("typealias $name =")
        values.forEachIndexed { index, value ->
            val prefix = if (index == 0) "  " else "  | "
            appendLine("$prefix\"${escapePklString(value)}\"")
        }
    }

    private fun escapePklString(value: String): String = value.replace("\\", "\\\\").replace("\"", "\\\"")

    private data class SourceText(
        val name: String,
        val text: String,
    )
}
