"""Generates RulesIndex.pkl listing every rule module with an explicit import.

Replaces the runtime-glob pattern (`import*("rules/*.pkl")` in Catalog.pkl)
with build-time-resolved explicit imports. `modulepath:` is not globbable in
Pkl, so the runtime evaluator inside the Spring Boot fat JAR cannot resolve
`import*` against the classpath — see apple/pkl#572.
"""

def _to_pkl_identifier(basename):
    # ActivityLabelCapitalization.pkl -> activityLabelCapitalization
    name = basename[:-len(".pkl")] if basename.endswith(".pkl") else basename
    if not name:
        fail("empty rule basename")
    return name[0].lower() + name[1:]

def _rules_index_impl(ctx):
    output = ctx.outputs.out

    rule_files = sorted(ctx.files.srcs, key = lambda f: f.basename)

    lines = [
        "// Generated by Bazel target {}.".format(ctx.label),
        "// Do not edit by hand. Regenerate with `bazel build {}`.".format(ctx.label),
        "//",
        "// Imports every rule module under rules/ at build time so the runtime",
        "// evaluator does not need to glob the classpath (which Pkl forbids for",
        "// modulepath: — only file: and package: are globbable).",
        "",
    ]

    aliases = []
    for f in rule_files:
        alias = _to_pkl_identifier(f.basename)
        lines.append('import "rules/{}" as {}'.format(f.basename, alias))
        aliases.append(alias)

    lines.append("")
    lines.append("local ruleList: List = List(")
    for alias in aliases:
        lines.append("  {},".format(alias))
    lines.append(")")
    lines.append("")
    lines.append("rules = ruleList.sortBy((r) -> r.id)")
    lines.append("")

    ctx.actions.write(
        output = output,
        content = "\n".join(lines),
    )
    return [DefaultInfo(files = depset([output]))]

rules_index = rule(
    implementation = _rules_index_impl,
    attrs = {
        "srcs": attr.label_list(
            allow_files = [".pkl"],
            mandatory = True,
            doc = "Rule .pkl files to import explicitly in RulesIndex.pkl.",
        ),
        "out": attr.output(
            mandatory = True,
            doc = "Output Pkl module path, typically RulesIndex.pkl.",
        ),
    },
    doc = "Emits a Pkl module that imports every rule file and exposes a sorted `rules` list.",
)
