spring:
  autoconfigure:
    exclude:
      - com.embabel.agent.autoconfigure.models.anthropic.AgentAnthropicAutoConfiguration

embabel:
  agent:
    platform:
      models:
        default-llm: "gpt-4o"
        openai:
          base-url: "https://models.github.ai/inference"
          api-key: ${GITHUB_TOKEN}

bpmner:
  model: "gpt-4o"
