spring:
  autoconfigure:
    exclude:
      - com.embabel.agent.autoconfigure.models.openai.AgentOpenAiAutoConfiguration

embabel:
  models:
    default-llm: claude-sonnet-4-0

bpmner:
  max-attempts: 8
  model: claude-sonnet-4-0
