/*
 * Copyright 2026 The Project Contributors
 * SPDX-License-Identifier: MIT
 */

/*
 * These data classes mirror the typed config subclasses in
 * `linter/pkl/schema/CheckPrimitive.pkl`. They are hand-authored rather than generated by
 * `pkl-codegen-kotlin` because:
 *
 *  1. The codegen emits open classes, not the sealed hierarchy we want for exhaustive
 *     `when`-dispatch and Jackson `@JsonSubTypes` polymorphism.
 *  2. `rules_pkl` 0.15 has no Bazel `pkl_kotlin_library` rule, so a custom genrule + a
 *     post-processor (open → sealed) would be needed.
 *  3. Pkl constraints like `String(!isEmpty)` don't translate to Kotlin types — validation
 *     still happens at the load boundary either way.
 *
 * Net trade for ~10 small configs (~100 lines): hand-authoring is cheaper than building
 * and maintaining the codegen pipeline. Revisit in Phase 3 if the config surface grows past
 * ~30 types.
 */

package dev.groknull.bpmner.rules.internal.domain.primitives

/**
 * Marker for the typed configs of the 10 deterministic check primitives. `SubCheckConfig`
 * accepts only this type, so `CompositeCheck` cannot embed a `CompositeCheckConfig`
 * (no nesting) or an `LlmCheckRuleConfig` (different evaluation tier) at compile time —
 * what was a runtime `rule-config-error` is now caught by the Kotlin type system.
 *
 * Pkl-side enforcement of the same constraint lives in `CheckPrimitive.pkl`'s `SubCheck`
 * doc comment; this sealed hierarchy is the in-process backstop.
 */
internal sealed interface DeterministicCheckConfig

internal data class RequiredPropertyCheckConfig(
    val property: String,
) : DeterministicCheckConfig

internal data class PropertyPatternCheckConfig(
    val property: String,
    val pattern: String,
    val patternDescription: String? = null,
    val forbiddenVocabulary: List<String>? = null,
    val allowedVocabulary: List<String>? = null,
) : DeterministicCheckConfig

internal data class VocabularyCheckConfig(
    val property: String,
    val mode: VocabularyMode,
    val words: List<String>,
    // When set, the check only applies to elements that carry this property (presence test);
    // elements lacking it pass silently. Lets a vocabulary check scope to a subset (e.g. only
    // multi-instance tasks) without re-typing the element. No-op when null.
    val appliesWhenProperty: String? = null,
) : DeterministicCheckConfig

internal enum class VocabularyMode {
    REQUIRE,
    FORBID,
    REQUIRE_LEADING,
    FORBID_LEADING,
}

internal data class RequiredAssociationCheckConfig(
    val association: String,
    val sourceTypes: List<String> = emptyList(),
    val targetTypes: List<String> = emptyList(),
    // OUTBOUND: the targeted element must be the association's sourceRef (e.g. a task linking
    // out to its annotation). INBOUND: the targeted element must be the targetRef (e.g. an
    // annotation that must be referenced by some element). BPMN models the element→annotation
    // association with sourceRef=element, so annotation-side checks need INBOUND.
    val direction: AssociationDirection = AssociationDirection.OUTBOUND,
    // Presence-test narrowing — see [VocabularyCheckConfig.appliesWhenProperty]. No-op when null.
    val appliesWhenProperty: String? = null,
) : DeterministicCheckConfig

internal enum class AssociationDirection {
    OUTBOUND,
    INBOUND,
}

internal data class TopologyCheckConfig(
    val topology: TopologyMode,
    val minIncoming: Int? = null,
    val maxIncoming: Int? = null,
    val minOutgoing: Int? = null,
    val maxOutgoing: Int? = null,
) : DeterministicCheckConfig

internal enum class TopologyMode {
    NO_FAKE_JOIN,
    NO_SUPERFLUOUS,
    NO_JOIN_FORK,
    CONVERGING_UNNAMED,
}

internal data class ConnectivityCheckConfig(
    val mode: ConnectivityMode,
    val sourceTypes: List<String> = emptyList(),
    val targetTypes: List<String> = emptyList(),
) : DeterministicCheckConfig

internal enum class ConnectivityMode {
    NO_INCOMING,
    FLOWS_NAMED,
    WITHIN_POOL,
    ACROSS_POOLS,
}

internal data class PairingCheckConfig(
    val mode: PairingMode,
    val left: String? = null,
    val right: String? = null,
) : DeterministicCheckConfig

internal enum class PairingMode {
    ERROR_END_BOUNDARY,
    LINK_PAIRING,
    MESSAGE_START_FLOW,
}

internal data class CardinalityCheckConfig(
    val element: String,
    val min: Int? = null,
    val max: Int? = null,
) : DeterministicCheckConfig

internal data class PoolLabelCheckConfig(
    val mode: PoolLabelMode,
) : DeterministicCheckConfig

internal enum class PoolLabelMode {
    WHITE_BOX_NAMED_BY_PROCESS,
    BLACK_BOX_NAMED_BY_EXTERNAL_ENTITY_OR_PROCESS,
    CHILD_DIAGRAMS_KEEP_POOL_PROCESS_NAME,
    LANE_LABELS_BUSINESS_ROLES_PERFORMERS,
}

internal data class ElementConstraintCheckConfig(
    val element: String,
    val mode: ElementConstraintMode,
    val constraints: Map<String, Any?> = emptyMap(),
) : DeterministicCheckConfig

internal enum class ElementConstraintMode {
    ALLOWED_ELEMENT_SUBSET,
    TIMER_EXPRESSION,
    PARALLEL_GATEWAY_STRUCTURE,
    EVENT_BASED_GATEWAY_DIRECT_EVENTS,

    // Boundary-event structural constraints (#183). Each targets bpmn:BoundaryEvent and owns one
    // sub-check of the BoundaryEventConstraints composite rule.
    BOUNDARY_ATTACHED,
    BOUNDARY_SINGLE_OUTGOING,
    BOUNDARY_ERROR_INTERRUPTING,
}

// ---------------------------------------------------------------------------------------
// Phase 3 (#218) NLP-aware primitives. Each takes a [BpmnNlp] facade at evaluation time —
// see SubCheckEvaluator for the dispatch wiring.

internal data class PartOfSpeechCheckConfig(
    val property: String,
    val mode: PartOfSpeechMode,
    val posClass: NlpPosTag,
) : DeterministicCheckConfig

internal enum class PartOfSpeechMode {
    LEADING_MUST_BE,
    LEADING_MUST_NOT_BE,
}

/**
 * Pkl-side mirror of [dev.groknull.bpmner.rules.internal.domain.nlp.PosTag]. Lives in this
 * file so the Pkl config DSL doesn't need to import the `nlp` package — the loader maps
 * one to the other in [dev.groknull.bpmner.rules.internal.domain.mapping.CheckConfigMapper].
 */
internal enum class NlpPosTag {
    VERB,
    NOUN,
    ADJ,
    AUX,
    WH,
    OTHER,
}

internal data class LemmaCheckConfig(
    val property: String,
    val mode: LemmaMode,
    val lemmas: List<String>,
) : DeterministicCheckConfig

internal enum class LemmaMode {
    REQUIRE_LEADING_LEMMA,
    FORBID_LEADING_LEMMA,
    REQUIRE_ANY_LEMMA,
    FORBID_ANY_LEMMA,
}

internal data class GrammaticalShapeCheckConfig(
    val property: String,
    val mode: GrammaticalShape,
) : DeterministicCheckConfig

internal enum class GrammaticalShape {
    /** Leading token is a noun OR a past-participle verb (`Order received`, `Payment failed`). */
    STATE_LABEL,

    /** Leading token is an action verb (`Process the order`). */
    ACTION_LABEL,

    /**
     * Label is question-shaped: leading token is a WH-word or modal/copular auxiliary, OR
     * the label ends with `?`.
     */
    QUESTION_FORM,
}

/**
 * Composite primitive config — composes deterministic sub-checks. See
 * [linter/pkl/schema/CheckPrimitive.pkl](linter/pkl/schema/CheckPrimitive.pkl) for the
 * authoritative shape. Note that `CompositeCheckConfig` itself is NOT a
 * `DeterministicCheckConfig` — nesting is rejected by the type system (you cannot pass a
 * `CompositeCheckConfig` to a `SubCheckConfig.config` field).
 */
internal data class CompositeCheckConfig(
    val targetTypes: List<String> = emptyList(),
    val subChecks: List<SubCheckConfig> = emptyList(),
)

internal data class SubCheckConfig(
    val diagnosticCode: String,
    val config: DeterministicCheckConfig,
)
