/*
 * Copyright 2026 The Project Contributors
 * SPDX-License-Identifier: MIT
 */

package dev.groknull.bpmner.layout.internal.adapter.outbound

import dev.groknull.bpmner.layout.BpmnAutoLayoutException
import org.camunda.bpm.model.bpmn.Bpmn
import org.camunda.bpm.model.bpmn.BpmnModelInstance
import org.camunda.bpm.model.bpmn.instance.FlowNode
import org.camunda.bpm.model.bpmn.instance.Group
import org.camunda.bpm.model.bpmn.instance.SequenceFlow
import org.camunda.bpm.model.bpmn.instance.TextAnnotation
import org.camunda.bpm.model.bpmn.instance.bpmndi.BpmnDiagram
import org.camunda.bpm.model.bpmn.instance.bpmndi.BpmnEdge
import org.camunda.bpm.model.bpmn.instance.bpmndi.BpmnLabel
import org.camunda.bpm.model.bpmn.instance.bpmndi.BpmnPlane
import org.camunda.bpm.model.bpmn.instance.bpmndi.BpmnShape
import org.camunda.bpm.model.bpmn.instance.dc.Bounds
import org.camunda.bpm.model.bpmn.instance.di.Waypoint
import org.eclipse.elk.alg.layered.options.LayeredMetaDataProvider
import org.eclipse.elk.alg.layered.options.LayeredOptions
import org.eclipse.elk.core.RecursiveGraphLayoutEngine
import org.eclipse.elk.core.data.LayoutMetaDataService
import org.eclipse.elk.core.options.CoreOptions
import org.eclipse.elk.core.options.Direction
import org.eclipse.elk.core.options.EdgeRouting
import org.eclipse.elk.core.options.HierarchyHandling
import org.eclipse.elk.core.util.BasicProgressMonitor
import org.eclipse.elk.graph.ElkEdge
import org.eclipse.elk.graph.ElkNode
import org.eclipse.elk.graph.util.ElkGraphUtil
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream

/**
 * Stateless, test-internal ELK layout path for the flat retained BPMN process graph.
 *
 * This class is NOT annotated with @Service or @SecondaryAdapter and is NOT wired into
 * BpmnLayoutPort. The GraalJS BpmnLayoutService remains the sole production authority until
 * the atomic 557-5 cutover. This path is exercised only by ElkBpmnLayouterTest.
 *
 * Input: BPMN XML string (any valid retained-profile flat process).
 * Output: same BPMN XML with all existing BPMN-DI removed and regenerated by ELK Layered.
 *
 * Architecture: AD-557-01..03 (plans/557/ARCHITECTURE.md).
 */
@Suppress("TooManyFunctions") // ELK-BPMN mapping has non-trivial branching per step; split into focused internal fns
internal class ElkBpmnLayouter {

    init {
        // ELK requires explicit algorithm registration when used without OSGi/SPI discovery.
        // Register once per class-loader: LayoutMetaDataService is a singleton that ignores
        // duplicate registrations, so this is safe to call on every instance construction.
        LayoutMetaDataService.getInstance().registerLayoutMetaDataProviders(
            LayeredMetaDataProvider(),
        )
    }

    @Suppress("ThrowsCount") // three distinct failure modes (parse, layout, serialize) — each is a correct throw
    fun layout(xml: String): String {
        val model = parseXml(xml)
        removeExistingDi(model)
        val (elkRoot, nodeMap, edgeMap) = buildElkGraph(model)
        runLayout(elkRoot)
        val (plane, shapeById) = writeDiNodeShapes(model, nodeMap)
        writeDiSequenceEdges(model, plane, edgeMap)
        writeDiAssociationEdges(model, plane, shapeById)
        return serializeXml(model)
    }

    // ── Parse / serialize ────────────────────────────────────────────────────────────────────────

    private fun parseXml(xml: String): BpmnModelInstance = try {
        Bpmn.readModelFromStream(ByteArrayInputStream(xml.toByteArray(Charsets.UTF_8)))
    } catch (e: org.camunda.bpm.model.xml.ModelParseException) {
        throw BpmnAutoLayoutException("ELK layout failed: could not parse BPMN XML: ${e.message}", e)
    }

    private fun serializeXml(model: BpmnModelInstance): String = try {
        val out = ByteArrayOutputStream()
        Bpmn.writeModelToStream(out, model)
        out.toString(Charsets.UTF_8)
    } catch (e: java.io.IOException) {
        throw BpmnAutoLayoutException("ELK layout failed: could not serialize BPMN XML: ${e.message}", e)
    }

    // ── Step 1: remove existing BPMN-DI ─────────────────────────────────────────────────────────

    private fun removeExistingDi(model: BpmnModelInstance) {
        model.getModelElementsByType(BpmnDiagram::class.java)
            .toList()
            .forEach { model.definitions.removeChildElement(it) }
    }

    // ── Step 2: build the ELK graph ──────────────────────────────────────────────────────────────

    private data class ElkGraphResult(
        val root: ElkNode,
        /** BPMN flow-node / annotation id → ElkNode */
        val nodeMap: Map<String, ElkNode>,
        /** BPMN sequence-flow id → ElkEdge */
        val edgeMap: Map<String, ElkEdge>,
    )

    private fun buildElkGraph(model: BpmnModelInstance): ElkGraphResult {
        val root = ElkGraphUtil.createGraph()
        applyLayoutOptions(root)
        val nodeMap = mutableMapOf<String, ElkNode>()
        val edgeMap = mutableMapOf<String, ElkEdge>()
        mapFlowNodes(model, root, nodeMap)
        mapSequenceFlows(model, nodeMap, edgeMap)
        mapAnnotations(model, root, nodeMap)
        mapGroups(model, root, nodeMap)
        return ElkGraphResult(root, nodeMap, edgeMap)
    }

    private fun mapFlowNodes(
        model: BpmnModelInstance,
        root: ElkNode,
        nodeMap: MutableMap<String, ElkNode>,
    ) {
        // Flat scope only — subprocesses/containment are 557-3. Boundary events included as
        // plain nodes so they receive DI and don't break coverage assertions.
        for (flowNode in model.getModelElementsByType(FlowNode::class.java).sortedBy { it.id }) {
            val elkNode = ElkGraphUtil.createNode(root)
            elkNode.identifier = flowNode.id
            val (w, h) = nodeDimensions(flowNode)
            elkNode.width = w
            elkNode.height = h
            val label = flowNode.name?.takeIf { it.isNotBlank() }
            if (label != null) {
                val elkLabel = ElkGraphUtil.createLabel(label, elkNode)
                val (lw, lh) = labelDimensions(label)
                elkLabel.width = lw
                elkLabel.height = lh
            }
            nodeMap[flowNode.id] = elkNode
        }
    }

    private fun mapSequenceFlows(
        model: BpmnModelInstance,
        nodeMap: Map<String, ElkNode>,
        edgeMap: MutableMap<String, ElkEdge>,
    ) {
        for (sf in model.getModelElementsByType(SequenceFlow::class.java).sortedBy { it.id }) {
            val sourceNode = nodeMap[sf.source?.id]
                ?: throw BpmnAutoLayoutException("ELK layout: flow '${sf.id}' source '${sf.source?.id}' not found")
            val targetNode = nodeMap[sf.target?.id]
                ?: throw BpmnAutoLayoutException("ELK layout: flow '${sf.id}' target '${sf.target?.id}' not found")
            val elkEdge = ElkGraphUtil.createSimpleEdge(sourceNode, targetNode)
            elkEdge.identifier = sf.id
            val edgeLabel = sf.name?.takeIf { it.isNotBlank() }
            if (edgeLabel != null) {
                val lbl = ElkGraphUtil.createLabel(edgeLabel, elkEdge)
                val (lw, lh) = labelDimensions(edgeLabel)
                lbl.width = lw
                lbl.height = lh
            }
            edgeMap[sf.id] = elkEdge
        }
    }

    private fun mapAnnotations(
        model: BpmnModelInstance,
        root: ElkNode,
        nodeMap: MutableMap<String, ElkNode>,
    ) {
        for (ann in model.getModelElementsByType(TextAnnotation::class.java).sortedBy { it.id }) {
            val elkNode = ElkGraphUtil.createNode(root)
            elkNode.identifier = ann.id
            elkNode.width = ANNOTATION_WIDTH
            elkNode.height = ANNOTATION_HEIGHT
            val labelText = ann.text?.textContent?.takeIf { it.isNotBlank() }
            if (labelText != null) {
                val lbl = ElkGraphUtil.createLabel(labelText, elkNode)
                val (lw, lh) = labelDimensions(labelText)
                lbl.width = lw
                lbl.height = lh
            }
            nodeMap[ann.id] = elkNode
        }
    }

    private fun mapGroups(
        model: BpmnModelInstance,
        root: ElkNode,
        nodeMap: MutableMap<String, ElkNode>,
    ) {
        for (group in model.getModelElementsByType(Group::class.java).sortedBy { it.id }) {
            val elkNode = ElkGraphUtil.createNode(root)
            elkNode.identifier = group.id
            elkNode.width = GROUP_WIDTH
            elkNode.height = GROUP_HEIGHT
            nodeMap[group.id] = elkNode
        }
    }

    private fun applyLayoutOptions(root: ElkNode) {
        root.setProperty(CoreOptions.ALGORITHM, LayeredOptions.ALGORITHM_ID)
        root.setProperty(CoreOptions.DIRECTION, Direction.RIGHT)
        root.setProperty(CoreOptions.EDGE_ROUTING, EdgeRouting.ORTHOGONAL)
        root.setProperty(CoreOptions.RANDOM_SEED, RANDOM_SEED)
        root.setProperty(CoreOptions.HIERARCHY_HANDLING, HierarchyHandling.SEPARATE_CHILDREN)
        root.setProperty(CoreOptions.SPACING_NODE_NODE, NODE_NODE_SPACING)
        root.setProperty(CoreOptions.SPACING_EDGE_NODE, EDGE_NODE_SPACING)
    }

    // ── Step 3: run layout ───────────────────────────────────────────────────────────────────────

    private fun runLayout(root: ElkNode) {
        RecursiveGraphLayoutEngine().layout(root, BasicProgressMonitor())
    }

    // ── Step 4: write BPMN-DI ────────────────────────────────────────────────────────────────────

    /** Extension: creates the single BPMNDiagram+BPMNPlane; returns the plane for further writes. */
    private val BpmnModelInstance.diPlane: BpmnPlane
        get() {
            val diagram = newInstance(BpmnDiagram::class.java)
            diagram.id = "BPMNDiagram_1"
            val plane = newInstance(BpmnPlane::class.java)
            plane.id = "BPMNPlane_1"
            getModelElementsByType(org.camunda.bpm.model.bpmn.instance.Process::class.java)
                .firstOrNull()?.let { plane.bpmnElement = it }
            diagram.bpmnPlane = plane
            definitions.addChildElement(diagram)
            return plane
        }

    /** Returns the freshly-created plane and a shape-by-BPMN-id map for downstream edge writes. */
    private fun writeDiNodeShapes(
        model: BpmnModelInstance,
        nodeMap: Map<String, ElkNode>,
    ): Pair<BpmnPlane, Map<String, BpmnShape>> {
        val plane = model.diPlane
        val shapeById = mutableMapOf<String, BpmnShape>()
        for (flowNode in model.getModelElementsByType(FlowNode::class.java).sortedBy { it.id }) {
            val elkNode = nodeMap[flowNode.id] ?: continue
            val shape = createNodeShape(model, flowNode, elkNode)
            plane.addChildElement(shape)
            shapeById[flowNode.id] = shape
        }
        for (ann in model.getModelElementsByType(TextAnnotation::class.java).sortedBy { it.id }) {
            val elkNode = nodeMap[ann.id] ?: continue
            val shape = model.newInstance(BpmnShape::class.java)
            shape.id = "BPMNShape_${ann.id}"
            shape.bpmnElement = ann
            shape.bounds = model.newBounds(elkNode.x, elkNode.y, elkNode.width, elkNode.height)
            plane.addChildElement(shape)
            shapeById[ann.id] = shape
        }
        for (group in model.getModelElementsByType(Group::class.java).sortedBy { it.id }) {
            val elkNode = nodeMap[group.id] ?: continue
            val shape = model.newInstance(BpmnShape::class.java)
            shape.id = "BPMNShape_${group.id}"
            shape.bpmnElement = group
            shape.bounds = model.newBounds(elkNode.x, elkNode.y, elkNode.width, elkNode.height)
            plane.addChildElement(shape)
            shapeById[group.id] = shape
        }
        return Pair(plane, shapeById)
    }

    private fun createNodeShape(model: BpmnModelInstance, flowNode: FlowNode, elkNode: ElkNode): BpmnShape {
        val shape = model.newInstance(BpmnShape::class.java)
        shape.id = "BPMNShape_${flowNode.id}"
        shape.bpmnElement = flowNode
        shape.bounds = model.newBounds(elkNode.x, elkNode.y, elkNode.width, elkNode.height)
        if (elkNode.labels.isNotEmpty()) {
            val elkLabel = elkNode.labels.first()
            val bpmnLabel = model.newInstance(BpmnLabel::class.java)
            bpmnLabel.bounds = model.newBounds(
                elkNode.x + elkLabel.x,
                elkNode.y + elkLabel.y,
                elkLabel.width,
                elkLabel.height,
            )
            shape.bpmnLabel = bpmnLabel
        }
        return shape
    }

    private fun writeDiSequenceEdges(model: BpmnModelInstance, plane: BpmnPlane, edgeMap: Map<String, ElkEdge>) {
        for (sf in model.getModelElementsByType(SequenceFlow::class.java).sortedBy { it.id }) {
            val elkEdge = edgeMap[sf.id] ?: continue
            val bpmnEdge = model.newInstance(BpmnEdge::class.java)
            bpmnEdge.id = "BPMNEdge_${sf.id}"
            bpmnEdge.bpmnElement = sf
            writeWaypoints(model, bpmnEdge, elkEdge)
            if (elkEdge.labels.isNotEmpty() && !sf.name.isNullOrBlank()) {
                val elkLabel = elkEdge.labels.first()
                val offsetX = elkEdge.sections.firstOrNull()?.startX ?: 0.0
                val offsetY = elkEdge.sections.firstOrNull()?.startY ?: 0.0
                val bpmnLabel = model.newInstance(BpmnLabel::class.java)
                bpmnLabel.bounds = model.newBounds(offsetX + elkLabel.x, offsetY + elkLabel.y, elkLabel.width, elkLabel.height)
                bpmnEdge.bpmnLabel = bpmnLabel
            }
            plane.addChildElement(bpmnEdge)
        }
    }

    private fun writeDiAssociationEdges(
        model: BpmnModelInstance,
        plane: BpmnPlane,
        shapeById: Map<String, BpmnShape>,
    ) {
        for (assoc in model.getModelElementsByType(org.camunda.bpm.model.bpmn.instance.Association::class.java)
            .sortedBy { it.id }) {
            val bpmnEdge = model.newInstance(BpmnEdge::class.java)
            bpmnEdge.id = "BPMNEdge_${assoc.id}"
            bpmnEdge.bpmnElement = assoc
            val (s1x, s1y) = shapeById[assoc.source?.id]?.let { shapeCenter(it) } ?: Pair(0.0, 0.0)
            val (s2x, s2y) = shapeById[assoc.target?.id]?.let { shapeCenter(it) } ?: Pair(0.0, 0.0)
            model.newWaypoint(s1x, s1y).also { bpmnEdge.waypoints.add(it) }
            model.newWaypoint(s2x, s2y).also { bpmnEdge.waypoints.add(it) }
            plane.addChildElement(bpmnEdge)
        }
    }

    private fun writeWaypoints(model: BpmnModelInstance, bpmnEdge: BpmnEdge, elkEdge: ElkEdge) {
        val section = elkEdge.sections.firstOrNull()
        if (section == null) {
            // Fallback: two zero waypoints so the edge still has minimal DI
            model.newWaypoint(0.0, 0.0).also { bpmnEdge.waypoints.add(it) }
            model.newWaypoint(0.0, 0.0).also { bpmnEdge.waypoints.add(it) }
            return
        }
        model.newWaypoint(section.startX, section.startY).also { bpmnEdge.waypoints.add(it) }
        for (bend in section.bendPoints) {
            model.newWaypoint(bend.x, bend.y).also { bpmnEdge.waypoints.add(it) }
        }
        model.newWaypoint(section.endX, section.endY).also { bpmnEdge.waypoints.add(it) }
    }

    // ── Model factory helpers ────────────────────────────────────────────────────────────────────

    private fun BpmnModelInstance.newBounds(x: Double, y: Double, w: Double, h: Double): Bounds {
        val b = newInstance(Bounds::class.java)
        b.x = x
        b.y = y
        b.width = w
        b.height = h
        return b
    }

    private fun BpmnModelInstance.newWaypoint(x: Double, y: Double): Waypoint {
        val wp = newInstance(Waypoint::class.java)
        wp.x = x
        wp.y = y
        return wp
    }

    // ── Dimension and label helpers ──────────────────────────────────────────────────────────────

    private fun nodeDimensions(flowNode: FlowNode): Pair<Double, Double> {
        val typeName = flowNode.elementType.typeName
        return when {
            typeName.contains("Event") -> Pair(EVENT_SIZE, EVENT_SIZE)
            typeName.contains("Gateway") -> Pair(GATEWAY_SIZE, GATEWAY_SIZE)
            else -> Pair(TASK_WIDTH, TASK_HEIGHT) // tasks, call activities, subprocesses
        }
    }

    private fun labelDimensions(text: String): Pair<Double, Double> {
        val width = (text.length * GLYPH_WIDTH).coerceAtLeast(LABEL_MIN_WIDTH)
        return Pair(width, LABEL_HEIGHT)
    }

    /** Returns (centerX, centerY) of a shape, defaulting to (0, 0) when bounds are absent. */
    private fun shapeCenter(shape: BpmnShape): Pair<Double, Double> {
        val b = shape.bounds ?: return Pair(0.0, 0.0)
        return Pair(b.x + b.width / 2.0, b.y + b.height / 2.0)
    }

    companion object {
        // Fixed non-zero seed for deterministic layout (AD-557-03)
        private const val RANDOM_SEED = 1

        // Canonical BPMN shape dimensions (flat; no configuration needed)
        private const val TASK_WIDTH = 100.0
        private const val TASK_HEIGHT = 80.0
        private const val EVENT_SIZE = 36.0
        private const val GATEWAY_SIZE = 50.0
        private const val ANNOTATION_WIDTH = 100.0
        private const val ANNOTATION_HEIGHT = 60.0
        private const val GROUP_WIDTH = 300.0
        private const val GROUP_HEIGHT = 200.0

        // Label sizing — fixed glyph approximation, no font metrics (plan §lean-design-5)
        private const val GLYPH_WIDTH = 7.0
        private const val LABEL_MIN_WIDTH = 20.0
        private const val LABEL_HEIGHT = 14.0

        // Spacing constants
        private const val NODE_NODE_SPACING = 30.0
        private const val EDGE_NODE_SPACING = 20.0
    }
}
