// Generated by linter/scripts/generate-static-rules.mjs. Do not edit by hand.
import adHocSubProcess from 'bpmnlint/rules/ad-hoc-sub-process';
import conditionalFlows from 'bpmnlint/rules/conditional-flows';
import endEventRequired from 'bpmnlint/rules/end-event-required';
import eventBasedGateway from 'bpmnlint/rules/event-based-gateway';
import eventSubProcessTypedStartEvent from 'bpmnlint/rules/event-sub-process-typed-start-event';
import fakeJoin from 'bpmnlint/rules/fake-join';
import global from 'bpmnlint/rules/global';
import labelRequired from 'bpmnlint/rules/label-required';
import linkEvent from 'bpmnlint/rules/link-event';
import noBpmndi from 'bpmnlint/rules/no-bpmndi';
import noComplexGateway from 'bpmnlint/rules/no-complex-gateway';
import noDisconnected from 'bpmnlint/rules/no-disconnected';
import noDuplicateSequenceFlows from 'bpmnlint/rules/no-duplicate-sequence-flows';
import noGatewayJoinFork from 'bpmnlint/rules/no-gateway-join-fork';
import noImplicitEnd from 'bpmnlint/rules/no-implicit-end';
import noImplicitSplit from 'bpmnlint/rules/no-implicit-split';
import noImplicitStart from 'bpmnlint/rules/no-implicit-start';
import noInclusiveGateway from 'bpmnlint/rules/no-inclusive-gateway';
import noOverlappingElements from 'bpmnlint/rules/no-overlapping-elements';
import singleBlankStartEvent from 'bpmnlint/rules/single-blank-start-event';
import singleEventDefinition from 'bpmnlint/rules/single-event-definition';
import startEventRequired from 'bpmnlint/rules/start-event-required';
import subProcessBlankStartEvent from 'bpmnlint/rules/sub-process-blank-start-event';
import superfluousGateway from 'bpmnlint/rules/superfluous-gateway';
import superfluousTermination from 'bpmnlint/rules/superfluous-termination';

import act01VerbObjectName from '../rules/act-01-verb-object-name';
import act02ActivityLabelCapitalization from '../rules/act-02-activity-label-capitalization';
import act03DiscouragedBusinessVerbs from '../rules/act-03-discouraged-business-verbs';
import act12LoopTaskAnnotation from '../rules/act-12-loop-task-annotation';
import act13MiTaskAnnotation from '../rules/act-13-mi-task-annotation';
import assoc01RequiredAnnotationAssociation from '../rules/assoc-01-required-annotation-association';
import data01NoTypeWordsInDataName from '../rules/data-01-no-type-words-in-data-name';
import evt01EventStateName from '../rules/evt-01-event-state-name';
import evt02EventStatePattern from '../rules/evt-02-event-state-pattern';
import evt10StartNoIncoming from '../rules/evt-10-start-no-incoming';
import evt11MessageStartHasMessageFlow from '../rules/evt-11-message-start-has-message-flow';
import evt13IntermediateEventNotAction from '../rules/evt-13-intermediate-event-not-action';
import evt14BoundaryEventConstraints from '../rules/evt-14-boundary-event-constraints';
import evt15ErrorEndBoundaryPair from '../rules/evt-15-error-end-boundary-pair';
import evt16LinkEventPairing from '../rules/evt-16-link-event-pairing';
import flow01SequenceFlowWithinPool from '../rules/flow-01-sequence-flow-within-pool';
import flow02DivergingFlowOutcomeLabel from '../rules/flow-02-diverging-flow-outcome-label';
import gen01KlopsAllowedElements from '../rules/gen-01-klops-allowed-elements';
import gen02NoDuplicateDiagrams from '../rules/gen-02-no-duplicate-diagrams';
import gtw01DivergingGatewayQuestion from '../rules/gtw-01-diverging-gateway-question';
import gtw02ConvergingGatewayUnnamed from '../rules/gtw-02-converging-gateway-unnamed';
import gtw03GatewayNoWorkLabel from '../rules/gtw-03-gateway-no-work-label';
import gtw11EventBasedDirectEvents from '../rules/gtw-11-event-based-direct-events';
import gtw12DivergingFlowNames from '../rules/gtw-12-diverging-flow-names';
import msg01MessageFlowAcrossPools from '../rules/msg-01-message-flow-across-pools';
import msg02MessageFlowNamePattern from '../rules/msg-02-message-flow-name-pattern';
import name01BusinessMeaningfulLabel from '../rules/name-01-business-meaningful-label';
import name02UncommonAbbreviations from '../rules/name-02-uncommon-abbreviations';
import name03NoElementTypeWords from '../rules/name-03-no-element-type-words';

export const rules: Record<string, unknown> = {
  'ad-hoc-sub-process': adHocSubProcess,
  'bpmnlint/ad-hoc-sub-process': adHocSubProcess,
  'conditional-flows': conditionalFlows,
  'bpmnlint/conditional-flows': conditionalFlows,
  'end-event-required': endEventRequired,
  'bpmnlint/end-event-required': endEventRequired,
  'event-based-gateway': eventBasedGateway,
  'bpmnlint/event-based-gateway': eventBasedGateway,
  'event-sub-process-typed-start-event': eventSubProcessTypedStartEvent,
  'bpmnlint/event-sub-process-typed-start-event': eventSubProcessTypedStartEvent,
  'fake-join': fakeJoin,
  'bpmnlint/fake-join': fakeJoin,
  'global': global,
  'bpmnlint/global': global,
  'label-required': labelRequired,
  'bpmnlint/label-required': labelRequired,
  'link-event': linkEvent,
  'bpmnlint/link-event': linkEvent,
  'no-bpmndi': noBpmndi,
  'bpmnlint/no-bpmndi': noBpmndi,
  'no-complex-gateway': noComplexGateway,
  'bpmnlint/no-complex-gateway': noComplexGateway,
  'no-disconnected': noDisconnected,
  'bpmnlint/no-disconnected': noDisconnected,
  'no-duplicate-sequence-flows': noDuplicateSequenceFlows,
  'bpmnlint/no-duplicate-sequence-flows': noDuplicateSequenceFlows,
  'no-gateway-join-fork': noGatewayJoinFork,
  'bpmnlint/no-gateway-join-fork': noGatewayJoinFork,
  'no-implicit-end': noImplicitEnd,
  'bpmnlint/no-implicit-end': noImplicitEnd,
  'no-implicit-split': noImplicitSplit,
  'bpmnlint/no-implicit-split': noImplicitSplit,
  'no-implicit-start': noImplicitStart,
  'bpmnlint/no-implicit-start': noImplicitStart,
  'no-inclusive-gateway': noInclusiveGateway,
  'bpmnlint/no-inclusive-gateway': noInclusiveGateway,
  'no-overlapping-elements': noOverlappingElements,
  'bpmnlint/no-overlapping-elements': noOverlappingElements,
  'single-blank-start-event': singleBlankStartEvent,
  'bpmnlint/single-blank-start-event': singleBlankStartEvent,
  'single-event-definition': singleEventDefinition,
  'bpmnlint/single-event-definition': singleEventDefinition,
  'start-event-required': startEventRequired,
  'bpmnlint/start-event-required': startEventRequired,
  'sub-process-blank-start-event': subProcessBlankStartEvent,
  'bpmnlint/sub-process-blank-start-event': subProcessBlankStartEvent,
  'superfluous-gateway': superfluousGateway,
  'bpmnlint/superfluous-gateway': superfluousGateway,
  'superfluous-termination': superfluousTermination,
  'bpmnlint/superfluous-termination': superfluousTermination,
  'klm/act-01-verb-object-name': act01VerbObjectName,
  'bpmnlint-plugin-klm/act-01-verb-object-name': act01VerbObjectName,
  'klm/act-02-activity-label-capitalization': act02ActivityLabelCapitalization,
  'bpmnlint-plugin-klm/act-02-activity-label-capitalization': act02ActivityLabelCapitalization,
  'klm/act-03-discouraged-business-verbs': act03DiscouragedBusinessVerbs,
  'bpmnlint-plugin-klm/act-03-discouraged-business-verbs': act03DiscouragedBusinessVerbs,
  'klm/act-12-loop-task-annotation': act12LoopTaskAnnotation,
  'bpmnlint-plugin-klm/act-12-loop-task-annotation': act12LoopTaskAnnotation,
  'klm/act-13-mi-task-annotation': act13MiTaskAnnotation,
  'bpmnlint-plugin-klm/act-13-mi-task-annotation': act13MiTaskAnnotation,
  'klm/assoc-01-required-annotation-association': assoc01RequiredAnnotationAssociation,
  'bpmnlint-plugin-klm/assoc-01-required-annotation-association': assoc01RequiredAnnotationAssociation,
  'klm/data-01-no-type-words-in-data-name': data01NoTypeWordsInDataName,
  'bpmnlint-plugin-klm/data-01-no-type-words-in-data-name': data01NoTypeWordsInDataName,
  'klm/evt-01-event-state-name': evt01EventStateName,
  'bpmnlint-plugin-klm/evt-01-event-state-name': evt01EventStateName,
  'klm/evt-02-event-state-pattern': evt02EventStatePattern,
  'bpmnlint-plugin-klm/evt-02-event-state-pattern': evt02EventStatePattern,
  'klm/evt-10-start-no-incoming': evt10StartNoIncoming,
  'bpmnlint-plugin-klm/evt-10-start-no-incoming': evt10StartNoIncoming,
  'klm/evt-11-message-start-has-message-flow': evt11MessageStartHasMessageFlow,
  'bpmnlint-plugin-klm/evt-11-message-start-has-message-flow': evt11MessageStartHasMessageFlow,
  'klm/evt-13-intermediate-event-not-action': evt13IntermediateEventNotAction,
  'bpmnlint-plugin-klm/evt-13-intermediate-event-not-action': evt13IntermediateEventNotAction,
  'klm/evt-14-boundary-event-constraints': evt14BoundaryEventConstraints,
  'bpmnlint-plugin-klm/evt-14-boundary-event-constraints': evt14BoundaryEventConstraints,
  'klm/evt-15-error-end-boundary-pair': evt15ErrorEndBoundaryPair,
  'bpmnlint-plugin-klm/evt-15-error-end-boundary-pair': evt15ErrorEndBoundaryPair,
  'klm/evt-16-link-event-pairing': evt16LinkEventPairing,
  'bpmnlint-plugin-klm/evt-16-link-event-pairing': evt16LinkEventPairing,
  'klm/flow-01-sequence-flow-within-pool': flow01SequenceFlowWithinPool,
  'bpmnlint-plugin-klm/flow-01-sequence-flow-within-pool': flow01SequenceFlowWithinPool,
  'klm/flow-02-diverging-flow-outcome-label': flow02DivergingFlowOutcomeLabel,
  'bpmnlint-plugin-klm/flow-02-diverging-flow-outcome-label': flow02DivergingFlowOutcomeLabel,
  'klm/gen-01-klops-allowed-elements': gen01KlopsAllowedElements,
  'bpmnlint-plugin-klm/gen-01-klops-allowed-elements': gen01KlopsAllowedElements,
  'klm/gen-02-no-duplicate-diagrams': gen02NoDuplicateDiagrams,
  'bpmnlint-plugin-klm/gen-02-no-duplicate-diagrams': gen02NoDuplicateDiagrams,
  'klm/gtw-01-diverging-gateway-question': gtw01DivergingGatewayQuestion,
  'bpmnlint-plugin-klm/gtw-01-diverging-gateway-question': gtw01DivergingGatewayQuestion,
  'klm/gtw-02-converging-gateway-unnamed': gtw02ConvergingGatewayUnnamed,
  'bpmnlint-plugin-klm/gtw-02-converging-gateway-unnamed': gtw02ConvergingGatewayUnnamed,
  'klm/gtw-03-gateway-no-work-label': gtw03GatewayNoWorkLabel,
  'bpmnlint-plugin-klm/gtw-03-gateway-no-work-label': gtw03GatewayNoWorkLabel,
  'klm/gtw-11-event-based-direct-events': gtw11EventBasedDirectEvents,
  'bpmnlint-plugin-klm/gtw-11-event-based-direct-events': gtw11EventBasedDirectEvents,
  'klm/gtw-12-diverging-flow-names': gtw12DivergingFlowNames,
  'bpmnlint-plugin-klm/gtw-12-diverging-flow-names': gtw12DivergingFlowNames,
  'klm/msg-01-message-flow-across-pools': msg01MessageFlowAcrossPools,
  'bpmnlint-plugin-klm/msg-01-message-flow-across-pools': msg01MessageFlowAcrossPools,
  'klm/msg-02-message-flow-name-pattern': msg02MessageFlowNamePattern,
  'bpmnlint-plugin-klm/msg-02-message-flow-name-pattern': msg02MessageFlowNamePattern,
  'klm/name-01-business-meaningful-label': name01BusinessMeaningfulLabel,
  'bpmnlint-plugin-klm/name-01-business-meaningful-label': name01BusinessMeaningfulLabel,
  'klm/name-02-uncommon-abbreviations': name02UncommonAbbreviations,
  'bpmnlint-plugin-klm/name-02-uncommon-abbreviations': name02UncommonAbbreviations,
  'klm/name-03-no-element-type-words': name03NoElementTypeWords,
  'bpmnlint-plugin-klm/name-03-no-element-type-words': name03NoElementTypeWords,
};

export const config = {
  rules: {
  'ad-hoc-sub-process': 'error',
  'conditional-flows': 'error',
  'end-event-required': 'error',
  'event-based-gateway': 'error',
  'event-sub-process-typed-start-event': 'error',
  'fake-join': 'warn',
  'global': 'warn',
  'label-required': 'error',
  'link-event': 'error',
  'no-bpmndi': 'error',
  'no-complex-gateway': 'error',
  'no-disconnected': 'error',
  'no-duplicate-sequence-flows': 'error',
  'no-gateway-join-fork': 'error',
  'no-implicit-end': 'error',
  'no-implicit-split': 'error',
  'no-implicit-start': 'error',
  'no-inclusive-gateway': 'warn',
  'no-overlapping-elements': 'warn',
  'single-blank-start-event': 'error',
  'single-event-definition': 'error',
  'start-event-required': 'error',
  'sub-process-blank-start-event': 'error',
  'superfluous-gateway': 'warn',
  'superfluous-termination': 'warn',
  'klm/act-01-verb-object-name': 'warn',
  'klm/act-02-activity-label-capitalization': 'warn',
  'klm/act-03-discouraged-business-verbs': 'warn',
  'klm/act-12-loop-task-annotation': 'error',
  'klm/act-13-mi-task-annotation': 'error',
  'klm/assoc-01-required-annotation-association': 'error',
  'klm/data-01-no-type-words-in-data-name': 'error',
  'klm/evt-01-event-state-name': 'warn',
  'klm/evt-02-event-state-pattern': 'warn',
  'klm/evt-10-start-no-incoming': 'error',
  'klm/evt-11-message-start-has-message-flow': 'error',
  'klm/evt-13-intermediate-event-not-action': 'warn',
  'klm/evt-14-boundary-event-constraints': 'error',
  'klm/evt-15-error-end-boundary-pair': 'error',
  'klm/evt-16-link-event-pairing': 'error',
  'klm/flow-01-sequence-flow-within-pool': 'error',
  'klm/flow-02-diverging-flow-outcome-label': 'warn',
  'klm/gen-01-klops-allowed-elements': 'error',
  'klm/gen-02-no-duplicate-diagrams': 'error',
  'klm/gtw-01-diverging-gateway-question': 'warn',
  'klm/gtw-02-converging-gateway-unnamed': 'warn',
  'klm/gtw-03-gateway-no-work-label': 'warn',
  'klm/gtw-11-event-based-direct-events': 'error',
  'klm/gtw-12-diverging-flow-names': 'error',
  'klm/msg-01-message-flow-across-pools': 'error',
  'klm/msg-02-message-flow-name-pattern': 'warn',
  'klm/name-01-business-meaningful-label': 'warn',
  'klm/name-02-uncommon-abbreviations': 'warn',
  'klm/name-03-no-element-type-words': 'error',
  },
};

export const resolver = {
  resolveRule(pkg: string, name: string) {
    const combinations = [
      pkg ? `${pkg}/${name}` : name,
      name,
      `bpmnlint/${name}`,
      `klm/${name}`,
      `bpmnlint-plugin-klm/${name}`,
    ];

    for (const key of combinations) {
      const rule = rules[key];
      if (rule) {
        return typeof rule === 'object' && rule && 'default' in rule ? (rule as { default: unknown }).default : rule;
      }
    }

    return null;
  },
  resolveConfig(pkg: string, name: string) {
    if (pkg === 'bpmnlint' && name === 'recommended') {
      return config;
    }

    throw new Error(`Config resolution not supported in static resolver: ${pkg}/${name}`);
  },
};
