config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false

build:
  maxIssues: 0

style:
  MaxLineLength:
    maxLineLength: 130

complexity:
  TooManyFunctions:
    active: true
    ignoreOverridden: true
