/*
 * Copyright 2026 The Project Contributors
 * SPDX-License-Identifier: MIT
 */

package dev.groknull.bpmner.authoring.internal.adapter.outbound

import dev.groknull.bpmner.authoring.BpmnRenderer
import dev.groknull.bpmner.authoring.internal.adapter.outbound.BpmnModelFactory
import dev.groknull.bpmner.bpmn.BpmnDefinition
import dev.groknull.bpmner.bpmn.BpmnElementIndex
import dev.groknull.bpmner.bpmn.LaidOutProcessGraph
import dev.groknull.bpmner.bpmn.RenderedBpmn
import dev.groknull.bpmner.bpmn.RetryableBpmnGenerationException
import org.camunda.bpm.model.bpmn.Bpmn
import org.camunda.bpm.model.bpmn.BpmnModelInstance
import org.camunda.bpm.model.bpmn.instance.ConditionExpression
import org.camunda.bpm.model.bpmn.instance.Definitions
import org.camunda.bpm.model.bpmn.instance.ExclusiveGateway
import org.camunda.bpm.model.bpmn.instance.FlowNode
import org.camunda.bpm.model.bpmn.instance.InclusiveGateway
import org.camunda.bpm.model.bpmn.instance.Process
import org.camunda.bpm.model.bpmn.instance.SequenceFlow
import org.camunda.bpm.model.bpmn.instance.SubProcess
import org.camunda.bpm.model.bpmn.instance.bpmndi.BpmnDiagram
import org.camunda.bpm.model.xml.instance.ModelElementInstance
import org.jmolecules.architecture.hexagonal.SecondaryAdapter
import org.springframework.stereotype.Component
import java.io.ByteArrayOutputStream

@SecondaryAdapter
@Component
internal open class BpmnDefinitionToXmlConverter : BpmnRenderer {
    companion object {
        private const val TARGET_NAMESPACE = "https://groknull.dev/bpmner"

        private const val EXPORTER = "bpmner"
        private const val EXPORTER_VERSION = "0.0.1"
        private val UNUSED_DI_NAMESPACES_REGEX = Regex("\\s+xmlns:(?:bpmndi|omgdi|di|dc)=\"[^\"]*\"")
    }

    private val domPostProcessor = BpmnDefinitionDomPostProcessor()

    fun toXml(definition: BpmnDefinition): String = render(definition).xml

    override fun render(graph: LaidOutProcessGraph): RenderedBpmn {
        val rendered = render(graph.definition)
        return rendered.copy(sourceGraph = graph)
    }

    override fun render(definition: BpmnDefinition): RenderedBpmn {
        val modelInstance = toModelInstance(definition)
        val output = ByteArrayOutputStream()
        Bpmn.writeModelToStream(output, modelInstance)
        val xml = domPostProcessor.postProcess(output.toString(Charsets.UTF_8), definition)
        return RenderedBpmn(
            definition = definition,
            xml = stripUnusedDiNamespaces(xml),
            elementIndex = buildElementIndex(definition),
        )
    }

    // Camunda's writer auto-emits `xmlns:bpmndi` even when no diagram interchange elements are
    // present. We render semantic XML only; the downstream auto-layout stage adds BPMNDI. Strip
    // the unused namespace declaration so the output is clean and our own strict parser accepts
    // a round-trip.
    private fun stripUnusedDiNamespaces(xml: String): String = xml.replace(UNUSED_DI_NAMESPACES_REGEX, "")

    private fun toModelInstance(definition: BpmnDefinition): BpmnModelInstance {
        val modelInstance =
            Bpmn
                .createExecutableProcess(definition.processId)
                .name(definition.processName)
                .done()

        val process =
            modelInstance
                .getModelElementsByType(Process::class.java)
                .firstOrNull()
                ?: error("Unable to locate process in Camunda model instance")

        val definitions =
            modelInstance.definitions
                ?: error("Unable to locate definitions in Camunda model instance")
        configureDefinitions(definitions)

        val nodeMap = buildNodeMap(modelInstance, definition, process)
        buildSequenceFlows(modelInstance, definition, process, nodeMap)
        removeAutoGeneratedDiagramInterchange(modelInstance, definitions)
        return modelInstance
    }

    // `Bpmn.createExecutableProcess(...)` auto-creates an empty <bpmndi:BPMNDiagram> skeleton.
    // We don't want any BPMNDI in semantic-only output, so drop it before serialization.
    private fun removeAutoGeneratedDiagramInterchange(
        modelInstance: BpmnModelInstance,
        definitions: Definitions,
    ) {
        modelInstance
            .getModelElementsByType(BpmnDiagram::class.java)
            .toList()
            .forEach { definitions.removeChildElement(it) }
    }

    private fun buildNodeMap(
        modelInstance: BpmnModelInstance,
        definition: BpmnDefinition,
        process: Process,
    ): Map<String, FlowNode> {
        // Create every flow node up front (detached), so a nested node can resolve its
        // subprocess parent from the map regardless of where its parent sits in the flat list.
        val nodeMap = definition.nodes.associate { node ->
            node.id to BpmnModelFactory.newFlowNode(modelInstance, node)
        }
        // Attach each node to its container: the process for a top-level node, or the enclosing
        // SubProcess element for a nested one. Parent subprocesses are already in nodeMap, so a
        // subprocess nested inside a subprocess attaches correctly at any depth.
        for (node in definition.nodes) {
            containerFor(node.parentRef, nodeMap, process).addChildElement(nodeMap.getValue(node.id))
        }
        return nodeMap
    }

    // Resolves the BPMN container a node or edge belongs to: the process when [parentRef] is null,
    // otherwise the SubProcess flow node it names. Both Process and SubProcess accept child flow
    // elements via addChildElement.
    private fun containerFor(
        parentRef: String?,
        nodeMap: Map<String, FlowNode>,
        process: Process,
    ): ModelElementInstance {
        if (parentRef == null) return process
        return nodeMap[parentRef] as? SubProcess
            ?: throw IllegalArgumentException(
                "parentRef '$parentRef' does not resolve to a subprocess node",
            )
    }

    @Suppress("ThrowsCount") // 3 throws is the minimum needed for this function
    private fun buildSequenceFlows(
        modelInstance: BpmnModelInstance,
        definition: BpmnDefinition,
        process: Process,
        nodeMap: Map<String, FlowNode>,
    ) {
        for (edge in definition.sequences) {
            val source =
                nodeMap[edge.sourceRef]
                    ?: throw IllegalArgumentException("Unknown sourceRef '${edge.sourceRef}' on edge '${edge.id}'")
            val target =
                nodeMap[edge.targetRef]
                    ?: throw IllegalArgumentException("Unknown targetRef '${edge.targetRef}' on edge '${edge.id}'")
            val sequenceFlow = modelInstance.newInstance(SequenceFlow::class.java)
            sequenceFlow.id = edge.id
            if (!edge.name.isNullOrBlank()) sequenceFlow.name = edge.name
            if (!edge.conditionExpression.isNullOrBlank()) {
                val conditionExpression = modelInstance.newInstance(ConditionExpression::class.java)
                conditionExpression.textContent = edge.conditionExpression
                sequenceFlow.conditionExpression = conditionExpression
            }
            sequenceFlow.source = source
            sequenceFlow.target = target
            // An edge sits wholly in one scope (BPMN forbids flows crossing a subprocess
            // boundary), so it attaches to the same container its parentRef names.
            containerFor(edge.parentRef, nodeMap, process).addChildElement(sequenceFlow)
            source.outgoing.add(sequenceFlow)
            target.incoming.add(sequenceFlow)
            if (edge.isDefault) {
                when (source) {
                    is ExclusiveGateway -> source.default = sequenceFlow

                    is InclusiveGateway -> source.default = sequenceFlow

                    else ->
                        throw RetryableBpmnGenerationException(
                            "edge ${edge.id}: isDefault is only supported on exclusive- or inclusive-gateway " +
                                "sources, got ${source::class.simpleName}",
                        )
                }
            }
        }
    }

    private fun configureDefinitions(definitions: Definitions) {
        definitions.targetNamespace = TARGET_NAMESPACE
        definitions.exporter = EXPORTER
        definitions.exporterVersion = EXPORTER_VERSION
    }

    private fun buildElementIndex(definition: BpmnDefinition): BpmnElementIndex = BpmnElementIndex(
        processId = definition.processId,
        nodeObjectRefs = definition.nodes.associate { it.id to "nodes[id=${it.id}]" },
        edgeObjectRefs = definition.sequences.associate { it.id to "sequences[id=${it.id}]" },
    )
}
